### ISSUE TITLE
Genesis block (500m ZNC generated)

### ISSUE THREAD

**Issue by danimesq** [ZeroCoinOrganization/Zerocoin-wallet#4]
- [ ] 500m for the Open Fund
- [ ] OF haves its own privatekey
- [ ] OF managed by some developers
- [ ] Blocks are generated by Open Fund, to store transactions from users
- [ ] Prevent double spent, using merkle threes

**Comment by danimesq** [comment]
@imachug

**Comment by purplesyringa** [comment]
Oh. My. God. Are you building a blockchain in ZeroNet?

If you are, I replace `you` with `we` and ask: Are *we* building a blockchain in ZeroNet?

**Comment by danimesq** [comment]
@imachug

> Are we building a blockchain in ZeroNet?

Yes, because of it I mentioned you.
As created a PeerMessage plugin, you have some knowledge about how implement a basic blockchain on ZeroNet.
Basic, and centralized, but while we don't make it beta/stable.

The genesis block haves no sender, just registering that the OF (Open Fund, that haves a privatekey) haves 500m ZNC (Zerocoins).

**Comment by purplesyringa** [comment]
Personally, I don't know much about blockchains, but I think I know how they work.

So, are we making Etherium or BitCoin? I.e. will we have some logic or just money?

**Comment by danimesq** [comment]
@imachug 
I invited you as admin: https://github.com/ZeroNetPlus/Zerocoin/invitations

> So, are we making Etherium or BitCoin?

For now, something like Bitcoin, but more like Ripple, since it is centralized because we have no enough knowledge to make it decentralized.
But after some implementations, we need to make it full-decentralized and scalable unlike some other blockchains.

> I.e. will we have some logic or just money?

Beginning, just a cryptocurrency to fund ZeroNet and other related projects.

After some works, we will make an crowdsale (another 500m available, but as Ethereum placeholder tokens), and rename/rebrand it as Zerum blockchain, supporting smart contracts on scalable sidechains.

**Comment by purplesyringa** [comment]
>  I invited you as admin: https://github.com/ZeroNetPlus/Zerocoin/invitations

Thank you.

**Comment by danimesq** [comment]
A blockchain (merkle three), maybe using some of Git features.
You can make a Git plugin, that also works as archive for zites.

**Comment by danimesq** [comment]
@imachug
This repo is of the wallet (cointaining the blockchain), that is a merged site of the main site.

As ZeroNet uses Bitcoin cryptography, Zerocoin will use Bitcoin address. Maybe we can import transactions of Bitcoin, like BCH did? (it will attract Bitcoin users, like a fork)
The block 0 will contain the data telling that the Open Fund (a privatekey managed by me, you and any other developer we trust) haves 500,000,000 ZNC.
This genesis block can contain data based on Bitcoin, such as coin name, symbol, etc.

The next block (issue #5) will be about our transactions (as we manage the OF's privatekey) to developer's address, to help them fund their projects.

**Comment by danimesq** [comment]
To remember, it is not a mineable currency, but centralized, as test, while we can't make it more reliable.

**Comment by purplesyringa** [comment]
By the way, I'm not sure whether Git is what we can use. First, if we add a Git plugin, we have to make it secure, because size limits won't apply there. We'll also have `git` to be installed. Though this may not be a problem when there aren't miners, if we're going to scale, that's going to be a huge problem.

My solution is to simulate how BitCoin works.

1. Anyone can create a transaction he's going to make in his `data/users/.../data.dat`, where `data.dat` is a binary file. The data file is published, and the transaction is also sent via PeerMessage.
2. The miners (in the simpliest case, the Open Fund) check all the transactions the way they want (see below) and mine them. In the Open Fund case, mining looks like signing the block with Open Fund's private key. In case anyone can mine, it looks like adding a nonce till the block starts with `00000` or something like that -- we'll have to make some experiments here or use BitCoin's code.
3. The mined blocks are saved to `data/users/.../blocks.dat` (in binary format) and published via PeerMessage.
4. The users can now handle the new block.

## Mining algorithm

The mining algorithm could looks like this:

1. If there are at least 10 transactions, go to 6.
2. Wait for 10 seconds.
3. If there are at least 10 transactions, go to 6.
4. Mine all the transactions that exist.
5. Go to 1.
6. Mine some 10 transactions.

## Transaction format

The transaction format should looks like this:

```
+-----------+----------------------+
| 4b length |         data         |
+-----------+----------------------+
```

In `data.dat`, the transactions are just joined one-after-one.

This format can be used in several ways. In case we have BitCoin, we can use:

```
+--------+-------------------------+-----------+
| 1b 'T' | 64b destination address | 4b amount |
+--------+-------------------------+-----------+
```

The *real* destination address is generated as `[0x04] + destination_address` (see https://en.bitcoin.it/w/images/en/4/48/Address_map.jpg).

## Block format

There will be two kinds of blocks, the first one for Open Fund and another one for miners.

Open Fund:

```
+--------+---------------+--------------+---------------+---------------+-----+---------------+
| 1b 'F' | 72b signature | 4b tr. count | transaction 1 | transaction 2 | ... | transaction N |
+--------+---------------+--------------+---------------+---------------+-----+---------------+
```

Miners:

```
+--------+-------------------+----------+--------------+---------------+---------------+-----+---------------+
| 1b 'M' | 64b miner pub key | 8b nonce | 4b tr. count | transaction 1 | transaction 2 | ... | transaction N |
+--------+-------------------+----------+--------------+---------------+---------------+-----+---------------+
```

...Where `transaction` is defined as follows:

```
+--------------------+---------------------+
| 64b sender address | ?b user transaction |
+--------------------+---------------------+
```

The `miner pub key` field is where some amount of money is given if the block is valid. Again, it's generated like `[0x04] + miner_pub_key`.

## Admin rights for Open Fund

*This is under discussion.*

In fact, there will be 4 types of transactions.

### Transfer

```
+--------+-------------------------+-----------+
| 1b 'T' | 64b destination address | 4b amount |
+--------+-------------------------+-----------+
```

This kind of transactions means that we transfer `amount` money from `sender` (see *Block format* section) to `destination`.

These transactions can be created by all users.

### Add

```
+--------+-------------------------+-----------+
| 1b 'A' | 64b destination address | 4b amount |
+--------+-------------------------+-----------+
```

This adds `amount` money to `destination`. This command can only be issued by the Open Fund.

### Subtract

```
+--------+-------------------------+-----------+
| 1b 'U' | 64b destination address | 4b amount |
+--------+-------------------------+-----------+
```

This subtracts `amount` money from `destination`. This command can only be issued by the Open Fund.

### Set

```
+--------+-------------------------+-----------+
| 1b 'S' | 64b destination address | 4b amount |
+--------+-------------------------+-----------+
```

This gives `destination` exactly `amount` money. This command can only be issued by the Open Fund.

**Comment by danimesq** [comment]
@imachug 
Personally I don't liked the Add/Substract/Set transaction format, since it makes Zerocoin too much centralized, like a bank.
Not good to can create new coins, it will make Zerocoin worthless.
The better is to generate all available amounts in genesis block, where Open Funds haves 500 million ZNC that can distribute to developers/projects.

**Comment by danimesq** [comment]
"Miners" you mean the nodes/peers?
There will really have mining?

**Comment by purplesyringa** [comment]
Okay. It was just an example of different transactions, so ee can remove T probably.

**Comment by danimesq** [comment]
> Admin rights for Open Fund
> This is under discussion.

The admin rights for Open Fund is just for now, but after the launch of Zerum (ZBC), it will be fully decentralized. Maybe in care of miners/master nodes.

**Comment by danimesq** [comment]
We should make it Proof-of-Stack, but not for now, since it is proof-of-concept.
For now, just create the genesis block, and distribute transactions for developers (they are common nodes, but is nodes we choose to fund), and they can spent it to other nodes, for sample, to buy a .com domain in the forum's marketplace.

**Comment by danimesq** [comment]
I don't think pushing all Bitcoin's code is good, since it will require more efforts, but it is just a initial proof-of-concept, and we can make it simply work in some months or less.

**Comment by danimesq** [comment]
> Mining algorithm
> If there are at least 10 transactions, go to 6.
> Wait for 10 seconds.
> If there are at least 10 transactions, go to 6.
> Mine all the transactions that exist.
> Go to 1.
> Mine some 10 transactions.

Go to 6? What 6?
I didn't understood this.

What is the estimated number of transactions per second at this form?
Ripple can achieve 1,500 transactions per second, even more faster than Bitcoin.

**Comment by danimesq** [comment]
@imachug

**Comment by purplesyringa** [comment]
> Go to 6? What 6?

That algorithm is to mine at least 10 transactions. If there're less, wait for more. We can increase that to 1500, like in Ripple, and it'll be that fast.

**Comment by danimesq** [comment]
> We can increase that to 1500, like in Ripple, and it'll be that fast.

But what are the security implications of this increase?

**Comment by danimesq** [comment]
Do you think 1500 transactions is really possible?
Reference: #1

**Comment by purplesyringa** [comment]
We need about 5 machines in case we want the transactions to propogate at most 1 second. In case we just mean that it's okay that all the transactions wait 5 seconds till they're published, that's defenitely possible even with 1 machine.

**Comment by danimesq** [comment]
> We need about 5 machines in case we want the transactions to propogate at most 1 second. In case we just mean that it's okay that all the transactions wait 5 seconds till they're published, that's defenitely possible even with 1 machine.

@krixano @d14na

Do you want to be nodes?

**Comment by danimesq** [comment]
If they accept, then Zerocoin haves 4 machines.

**Comment by purplesyringa** [comment]
Hm... @shortcutme and @AnthyG?

**Comment by danimesq** [comment]
>We need about 5 machines in case we want the transactions to propogate at most 1 second. In case we just mean that it's okay that all the transactions wait 5 seconds till they're published, that's defenitely possible even with 1 machine.

@blurHY @tangdou1  @BenMcLean @rllola @slrslr @trenta3 @misses-robot @anoadragon453

**Comment by purplesyringa** [comment]
lol

**Comment by danimesq** [comment]
@imachug

What are the next things you think about it?

**Comment by slrslr** [comment]
@DaniellMesquita my Linux VPS can also be used to host an application (node?) if needed, just contact me once it is needed. But i have like 512MB RAM and like 10GB disk space and i would not guarantee 100% uptime. Btw. when reading this thread, i do not like the Bitcoin's proof of work concept because it is not eco friendly (too much electricity needed to confirm one stupid transaction). Though if this crypto will be low used project maybe not so big issue. Cloning and managing new crypto currency seems to me like full time task, i do not see any big reason to create it as a non developer/programmer. You think it is doable to make it popular and being useful/have some value? Though i am probably not a person that should be addressed in this project, as i am only a user, not a dev.

**Comment by danimesq** [comment]
> Though if this crypto will be low used project maybe not so big issue.

For while it is centralized, then not worry about it, in ZBC we can think in a eco friendly mining (proof-of-stack).

> Cloning and managing new crypto currency seems to me like full time task, i do not see any big reason to create it as a non developer/programmer. You think it is doable to make it popular and being useful/have some value? Though i am probably not a person that should be addressed in this project, as i am only a user, not a dev.

If you don't want, don't do it.
I was thinking that you would quickly/magically change your mind, and it happened.
![liar](https://user-images.githubusercontent.com/6765277/45600633-57ae9800-b9d6-11e8-8354-3156eb3174ff.png)

**Comment by AnthyG** [comment]
Hmm, I only have my main computer, and I can't and don't want to keep it on all the time, but if there's a way I can help, I'll try my best to do so (keep in mind that I am currently in my final year of school, so I don't have that much time on hand).

**Comment by rllola** [comment]
Why do you want to create another coin ?

**Comment by danimesq** [comment]
@rllola
> Why do you want to create another coin ?

Why do `they` want to boycott it?

**Comment by danimesq** [comment]
@slrslr

> If you don't want, don't do it.
> I was thinking that you would quickly/magically change your mind, and it happened.
> ![liar](https://user-images.githubusercontent.com/6765277/45600633-57ae9800-b9d6-11e8-8354-3156eb3174ff.png)

Oh, its you slrslr!
I throught was @imachug commenting that doesn't will develop it anymore (I had lots of partnered projects boycotted), because your avatars are very similar (Identicons). But I well supose Imachug will not want to work on Zerocoin, creating some reason. It happened once with other devs.

Sorry @slrslr @imachug @rllola .

I'm off to sleep and didn't throught well on reading.

**Comment by danimesq** [comment]
@slrslr 

> my Linux VPS can also be used to host an application (node?)

@imachug can answer how do it after, but yes, you can be a node with your VPS.

>if needed, just contact me once it is needed. But i have like 512MB RAM and like 10GB disk space and i would not guarantee 100% uptime.

Thanks, already helpful.

> Btw. when reading this thread, i do not like the Bitcoin's proof of work concept because it is not eco friendly (too much electricity needed to confirm one stupid transaction).

It will not use proof-of-work, and will be eco friendly since it doesn't haves mining.

> Though if this crypto will be low used project maybe not so big issue.

Not good if low used, then ZeroNet will also be low used.

> Cloning and managing new crypto currency seems to me like full time task, i do not see any big reason to create it as a non developer/programmer.

I didn't invited you to create it, but to help reach good transaction-per-second speed.

> You think it is doable to make it popular and being useful/have some value?

Yes, since in block 3 all Bitcoin's balances will be imported, acting like a hard fork.
If it gets popular, it will have worth (because it is scarce and fungible), then ZeroNet developers will can exchange coins to physical money, and be incentived to build ZeroNet better.

@AnthyG
> Hmm, I only have my main computer, and I can't and don't want to keep it on all the time, but if there's a way I can help, I'll try my best to do so

Thank you. When launched the block 1, I'll tell you. You will earn some ZNC, since you're a developer.

@rllola

> Why do you want to create another coin ?

Another?

**Comment by purplesyringa** [comment]
Well... I guess a coin is just a step. Come on, who needs another coin if we already have Bitcoin? But we have so many cryptocurrencies now... Using ZeroNet will help making blockchains easier. It'll be a great tool. So, it's like Etherium but *very* customizable. Do you remember that you can build Bitcoin in a few lines of Solidity? You'll be able to build Etherium with a few lines of JavaScript now.

**Comment by purplesyringa** [comment]
> I throught was @imachug commenting that doesn't will develop it anymore (I had lots of partnered projects boycotted), because your avatars are very similar (Identicons). But I well supose Imachug will not want to work on Zerocoin, creating some reason. It happened once, with @mkg20001 and other devs.

Well... Blockchain is an interesting thing I've always wanted to develop. It's awesome, in fact. ZeroNet is awesome as well. So why not merge two awesome things?.. Why would I create a reason not do something twice-awesome?!

**Comment by blurHY** [comment]
So there is a real ZeroCoin now. Does it use proof-of-work ? If it does,it will be waste of resource. I would not like to join the global warming

**Comment by purplesyringa** [comment]
Our Zerocoin will be a tool to build a blockchain. You can set any rules which define whether a block is correct. It can be a signature check in Open Fund case, or proof of work, or anything else you can imagine.

**Comment by trenta3** [comment]
@imachug Can you be more specific? The idea really attracts me, since I've also always wanted to create a new cryptocurrency.
How do you intend to build a tool to build a blockchain?
I've tried reading the organization repositories and site but I got lost.

**Comment by mkg20001** [comment]
@DaniellMesquita 
> But I well supose Imachug will not want to work on Zerocoin, creating some reason. It happened once, with @mkg20001 and other devs.

I'd appreceiate it if you wouldn't mention me as an example. I didn't "create" a reason. This wasn't the first project I dropped because it got boring and didn't seem like it was worth it.

With that said I'd still like to contribute towards this project. I could host a node, too.

**Comment by trenta3** [comment]
@DaniellMesquita Also is there any wiki page set up with some ideas or to start writing ideas about technical details?

I could also host a node

**Comment by purplesyringa** [comment]
I think we should use GitHub wiki for documentation. I'll put some ideas here now.

**Comment by trenta3** [comment]
@imachug I can't see in which wiki are you writing. All the wikis of the repositories of this organization redirect back to the repository code... Could you please insert link here to the wiki?

**Comment by purplesyringa** [comment]
Err... I haven't started writing it yet, maybe in a few hours. It'll be here: https://github.com/ZeroCoinOrganization/Documentation/wiki

**Comment by danimesq** [comment]
@imachug
> I guess a coin is just a step

It is the first step.

> who needs another coin if we already have Bitcoin?

Bitcoin doesn't directly funds ZeroNet.

> But we have so many cryptocurrencies now...

Lots of cryptocurrencies for promoting/funding projects, then ZeroNet also needs this.

> Using ZeroNet will help making blockchains easier.

Yes, remember Ethereum's CryptoKitties needed to rely on the slow IPFS to store images.

> It'll be a great tool.

If it is fast and very scalable, yes. But we shouldn't think about the blockchain platform now, but after we rebrand Zerocoin to Zerum blockchain platform.

> You'll be able to build Etherium with a few lines of JavaScript now.

Lisk already supports blockchains (side-chains) written on JavaScript, but I don't know if smart contract is supported.

> Blockchain is an interesting thing I've always wanted to develop. It's awesome, in fact. ZeroNet is awesome as well. So why not merge two awesome things?.. Why would I create a reason not do something twice-awesome?!

Yes, both cryptocurrency/blockchain platform (ZNC) free distributed hosting/reliable Internet network (ZN). Exchanges can install ZeroNet and list ZNC, but it will need RPC API.

@blurHY
> So there is a real ZeroCoin now. Does it use proof-of-work ? If it does,it will be waste of resource. I would not like to join the global warming

It is not mineable yet, but centralized by Open Fund. But when it turns into blockchain platform, maybe it can be proof-of-stack, or a web-friendly algorithm like what Monero uses.

@imachug
> Our Zerocoin will be a tool to build a blockchain. You can set any rules which define whether a block is correct. It can be a signature check in Open Fund case, or proof of work, or anything else you can imagine.

Open Fund managing independent blockchains?
I think we need to make it centralized but just for now, then rebrand it as Zerum and make it decentralized.

@trenta3 
> Can you be more specific? The idea really attracts me, since I've also always wanted to create a new cryptocurrency.
> How do you intend to build a tool to build a blockchain?

We can have inspiration on Lisk, to turn it into a platform for side-chains.

@mkg20001 
> I'd appreceiate it if you wouldn't mention me as an example.

Sorry, I removed it.

> I didn't "create" a reason. This wasn't the first project I dropped because it got boring and didn't seem like it was worth it.

Sure.

> With that said I'd still like to contribute towards this project. I could host a node, too.

Pull requests fixing bugs/vulnerabilities or improving something you want is very welcome. Thanks for offer node hosting, it will secure the network and make it faster, thanks.

@trenta3 
> @DaniellMesquita Also is there any wiki page set up with some ideas or to start writing ideas about technical details?

I'm writing a bit and creating titles.

> I could also host a node

Thanks! @imachug what do you think about ZNC coins for nodes? Maybe detecting lots of content publishings as proof-of-work, for sample, the transactions stored on nodes.
It can also spawn new programmed blocks automatically and verifiable, without relying on Open Fund to generate new blocks.
(but block 0-2 will need to be created by Open Fund, becase block 0 is the initial, block 1 is test transactions for ZeroNet developers/contributors, and block 2 is importing from Bitcoin balances)

@imachug 
> I think we should use GitHub wiki for documentation. I'll put some ideas here now.

> Err... I haven't started writing it yet, maybe in a few hours. It'll be here: https://github.com/ZeroCoinOrganization/Documentation/wiki

Thanks, me too, I need to create templates/titles on the wiki, for fill.

**Comment by danimesq** [comment]
Zerocoin's zite: http://127.0.0.1:43110/1ZCoinP3651Ecq8mgJtuQ7wAHpnG7v34v

**Comment by d14na** [comment]
@DaniellMesquita hey, been [OTG](http://127.0.0.1:43110/asklexi.bit?otg) for a bit, working on getting the first [Demo](https://github.com/d14na/zeronet-web-gateway) for [SUPeer](http://127.0.0.1:43110/supeer.bit) up and running asap. 

But, absolutely I love the idea of integrating Zeronet with crypto! I have VPS resources available and would be very very happy to support your project. I have very extensive experience with Blockchains (been in that game since '12) and I could definitely provide technical support. 

However, as you may already be aware, I'm already working on a token called ZeroGold. So I wouldn't be able to join your team, "officially", but I believe that ALL cryptos are welcome and will support any and all efforts to expand the Zeronet ecosystem.

**TL;DR** 

1. 0GOLD is a standard ERC-20 Ethereum token.
2. 0GOLD is a NEW type of mineable token (see [here](https://www.reddit.com/r/Tokenmining/comments/98v8v2/zerogold_pow_merged_mining/))
3. Most of the "Core" projects of Zer0net will integrate ZeroGold smart contracts in some way.

---

Creating a new blockchain is NOT a bad idea, as long as you have the community support to provide sufficient mining power to secure the chain. **This is NOT easy.** I think you're on the right track modeling after [Ripple](https://ripple.com/xrp/) and keeping it relatively centralized (ie very efficient), but I'd say also take a look at [Stellar](https://www.stellar.org/), as I believe their tech AND their team are much more user-friendly (as they came from the same place).

I've kinda of been over Bitcoin since the drama started in '16 with the block size wars. It really hurt (read. destroyed) one of my businesses and I well I'm still pretty bitter about the whole thing lol. I have several project coming out that will heavily rely on the [Ethereum Virtual Machine (EVM)](https://en.wikipedia.org/wiki/Ethereum) and smart contracts. And this is where my current focus is...

I see a problem with scalability on Zeronet, due to the FULL dataset of each zite being required to be downloaded, stored and updated for each peer. Using smart contracts, MUCH of that data can be stored in the EVM and simply accessed by the peers that need the data to interact with the zites. **CAVEAT IS, YOU NEED CRYPTO TO MAKE CHANGES ** So, whereas anyone can READ from the contracts, you have to PAY TO WRITE. Ethereum is very cheap now, so txs are like US$0.01 or so, but if that were to change, then it could become a problem for users that were heavy on community engagement.

Anyway, feel free to ask me anything about crypto and/or blockchains. If I don't have the answer, I certainly know the people who do. I wish you good luck!

**Comment by danimesq** [comment]
@d14na
zGold and ZNC are different projects with different purposes, and I agree that more than one cryptocurrency is good for the ecosystem.

> YOU NEED CRYPTO TO MAKE CHANGES ** So, whereas anyone can READ from the contracts, you have to PAY TO WRITE.

@april93
I don't think so, ZeroNet can really be scalable without need to pay even a little fraction of cent.
Telegram would be usable if users needed to pay 0.00001 cent for every message? Or Twitter charging 0.000000001 cent for every post?

Zerocoin need to be a blockchain that doesn't looks like a blockchain.

**Comment by mkg20001** [comment]
@DaniellMesquita 
> I don't think so, ZeroNet can really be scalable without need to pay even a little fraction of cent.
Telegram would be usable if users needed to pay 0.00001 cent for every message? Or Twitter charging 0.000000001 cent for every post?

(Note: I'm talking about the blockchain, not zeronet itself which already has such limits and protections in place)

Then there need to be strict rules to prevent people from just filling up everyones hard drives with garbage.
Because if everyone can write an unlimited amount this is going to get abused. (And - unless accounts are somehow verified - anyone can create an unlimited number of accounts so per-account limits are somewhat useless in that case)

And even if the _only_ thing that can be written into the blockchain are transcation: Without fees anyone can just take a non-zero amount of coins, split them to fractions accross hundreds of addresses and transfer them back-and-forth 24/7. That generates enough valid garbage to make the blockchain huge in a week.

(Just wanted to mention all ways this can go bad - not critising)

**Comment by d14na** [comment]
> Without fees anyone can just take a non-zero amount of coins, split them to fractions accross hundreds of addresses and transfer them back-and-forth 24/7. That generates enough valid garbage to make the blockchain huge in a week.

@DaniellMesquita this is referred to as a [Sybil attack](https://en.wikipedia.org/wiki/Sybil_attack); and it will quickly destroy ANY blockchain. **This is the reason why EVERY blockchain has some FEE (no matter how small) for EVERY modification made to the blockchain.** 

> I don't think so, ZeroNet can really be scalable without need to pay even a little fraction of cent.

I respectfully disagree.

I've been in this field for about 6 years now, and any project that's ever claimed to be fee-less has failed. Many, many, many have tried, but they all make promises they can't keep. Again, I'd strongly recommend you consider my Stellar recommendation, as they are one of the cheapest blockchains (or ledger if you want to be technical); and unless you're planning on doing a lot of smart contracts, probably the most mature for your purposes (primarily as a currency). Even if you don't build on top of their tech, you may consider just forking it and making it your own.

The OTHER problem, is that you CANNOT control the VALUE of your coin once its on the open market (ie trading on an exchange). So the cost per transaction will fluctuate and potentially become too expensive for the average user or someone with heavy engagement with the blockchain.

The bottom line is that these are problems that NO ONE has really solved yet. A LOT of people are trying though and there are HUGE rewards for the team that makes it happen. My bet is heavily weighted on Ethereum to eventually do it.

**Comment by danimesq** [comment]
@mkg20001
> Then there need to be strict rules to prevent people from just filling up everyones hard drives with garbage.
Because if everyone can write an unlimited amount this is going to get abused. (And - unless accounts are somehow verified - anyone can create an unlimited number of accounts so per-account limits are somewhat useless in that case

This is one of the greatest flaw of ZeroNet.

http://127.0.0.1:43110/zeromedium.bit/?/15hL2gR4oCSgKBbndn3MxY8Hc5xoy1vqCe/part-2-how-do-i-envision-zeronet-to-be-ready-for-mass-of-users

I proposed a verification system, but a user called it "nazi" and suggested users to pay on signup.
Well, I'm not too against it, but, we can think in a better approach, such as proof-of-work or any other algorithm to verify it.

> And even if the only thing that can be written into the blockchain are transcation: Without fees anyone can just take a non-zero amount of coins, split them to fractions accross hundreds of addresses and transfer them back-and-forth 24/7. That generates enough valid garbage to make the blockchain huge in a week.

Fees are a form to prevent a huge blockchain? And a maximum kb per transaction.
Also, after some development, we need to implement something like segwit/sharding.

**Comment by ghost** [comment]
You can't fill up a person's hard drive (without explicitly allowing it) with ZeroNet zites and data files because both zites and users have space limits.

**Comment by anoadragon453** [comment]
Do be aware that ZeroNet already has a Sybil mitigation system built in, where you have to manually approve large growth of a site's files.

On a blockchain this is a different story, however I doubt we talking about storing site contents on a blockchain.

A ZeroNet coin could only be used for domain registration and you'd already have a sleek blockchain with a very useful purpose.

**Comment by danimesq** [comment]
@d14na
> and any project that's ever claimed to be fee-less has failed.

I'm not against fees on Zerocoin, but on ZeroNet.

> I'd strongly recommend you consider my Stellar recommendation, as they are one of the cheapest blockchains (or ledger if you want to be technical); and unless you're planning on doing a lot of smart contracts, probably the most mature for your purposes (primarily as a currency).

What will be the function of Stellar?

> The OTHER problem, is that you CANNOT control the VALUE of your coin once its on the open market (ie trading on an exchange). So the cost per transaction will fluctuate and potentially become too expensive for the average user or someone with heavy engagement with the blockchain.

We can't change the value of coin, but we need to change the needed fee to not make it expensive.

**Comment by danimesq** [comment]
@krixano
> You can't fill up a person's hard drive with ZeroNet because both zites and users have space limits.

But think about a spam that makes a site grow from 20MB to 1GB. Users will need to be clicking the increase button?

**Comment by ghost** [comment]
Yeah, that's the protection against filling up HDD space *for ZeroNet Zites and data files*. I'm not recommending you do this for blockchain. I'm just pointing out that ZeroNet already has this protection, contrary to what you said ("This is one of the greatest flaw of ZeroNet.").

Additionally, zite owners can control the amount of space used by users and if someone goes over, the zite owner has to explicitly allow that.

**Comment by danimesq** [comment]
@anoadragon453
> Do be aware that ZeroNet already has a Sybil mitigation system built in, where you have to manually approve large growth of a site's files.

Only time and growth usage can show if this is enough.

> On a blockchain this is a different story, however I doubt we talking about storing site contents on a blockchain.

No need. But we can create a git archiving plugin, like Web Archive/Wayback Machine.

> A ZeroNet coin could only be used for domain registration and you'd already have a sleek blockchain with a very useful purpose.

I think you didn't readed about the purpose of Zerocoin.

**Comment by danimesq** [comment]
@krixano
> ZeroNet already has this protection, contrary to what you said ("This is one of the greatest flaw of ZeroNet.")

I said it because:

> But think about a spam that makes a site grow from 20MB to 1GB. Users will need to be clicking the increase button?

**Comment by danimesq** [comment]
List of needed things on ZeroNet:
https://github.com/HelloZeroNet/ZeroNet/issues/1621

**Comment by mkg20001** [comment]
> And even if the only thing that can be written into the blockchain are transcation: Without fees anyone can just take a non-zero amount of coins, split them to fractions accross hundreds of addresses and transfer them back-and-forth 24/7. That generates enough valid garbage to make the blockchain huge in a week.


Something that just came to my mind which might migtate this somewhat (aside from fees which also should be implemented): Implementing an algorithm that somehow calculates a number of blocks that an amount of funds can't be transferred.
(Note that this is a different idea than waiting N blocks to be mined after the transaction in order for it to be valid)

That algorithm would then do things like:
 - Make it so if a transaction transfers only a small amount of funds they are getting frozen for a much longer time than if the amount is big
 - Also add more freeze time depending on how little the previous transactions were in which those coins were involved (Would prevent people from repeateadly sending a small amount of coins back and forth)
   - This rule could also act in reverse so that coins that previously were in a huge transaction get a lower freeze time
 - Possibly some calculation based on how long the coins weren't being used

Note: With "amount" I mean total transaction value (but it should be possible to write the algorithm in such a way that it applies a different freeze time to every tx output) and with transaction I usually mean a complete transaction with multiple inputs/outputs

Edit: After writing this I realized that this (similar to fees) would suffer from changes in the coin's value. This might require a centralized "source of truth" or some algorithm that "estimates" the coins value based on chain activity (but this could also go more than horribly wrong and could be abused pretty easily with a bit of funds)

**Comment by purplesyringa** [comment]
> Bitcoin doesn't directly funds ZeroNet.

I guess you didn't understand what I meant. I said that sentence and then proved that it's wrong by giving Etherium as an example.

**Comment by danimesq** [comment]
@imachug

What are the first things on the development?
I mean, in what you will begin?

**Comment by d14na** [comment]
> What well be the function of Stellar?

Stellar is very similar to Bitcoin (serves a currency), but its more centralized and can be "controlled/managed" a lot better/easier. It's extremely mature *(currently being supported by large enterprises like IBM among others)* and it could potentially be used as the platform for your cryptocurrency. Not saying that you have to use Stellar's platform, but you could fork it and make it your own if that's what you prefer.

@DaniellMesquita OMG, its been a tough week for me, handling a lot of personal/family stuff, also, trying to get a new Zeronet client demo out asap; but I want to try my best to support your project as well 👍, really believe crypto needs to be more integrated with Zeronet.

Anyway, another thought that I've considered, in addition to my blockchain ideas, its creating a Zeronet [Web of Trust](https://en.wikipedia.org/wiki/Web_of_trust) *(aka a reputation system).* Might be similar to what @mkg20001 mentioned a few days back. This wouldn't require **cost,** but what it would **require** is the community's **time** in terms of **rating** each other. Simply put, you could then **UP VOTE** good actors and **DOWN VOTE** bad actors. This definitely falls under **"easier said than done",** but I think its worth an effort, as it would help to mitigate Sybil attacks, while also maintaining a fee-less structure.

**Comment by danimesq** [comment]
@d14na 
> Anyway, another thought that I've considered, in addition to my blockchain ideas, its creating a Zeronet Web of Trust (aka a reputation system). Might be similar to what @mkg20001 mentioned a few days back. This wouldn't require cost, but what it would require is the community's time in terms of rating each other. Simply put, you could then UP VOTE good actors and DOWN VOTE bad actors. This definitely falls under "easier said than done", but I think its worth an effort, as it would help to mitigate Sybil attacks, while also maintaining a fee-less structure.

I'll create a repo for this.
A reputation system with invites, votes, and user optionally can pay a small verification fee to build a greater trust.

@imachug 
> What are the first things on the development?
> I mean, in what you will begin?

**Comment by purplesyringa** [comment]
@DaniellMesquita 

First, we want to make a site for wallet so we need a site. I see there's https://github.com/ZeroCoinOrganization/Zerocoin-wallet, and it's empty. So I think I can put webpack there, as I'd want to use ES2017 features, like `import` of my local files and NPM packages.

I'd like to hear whether you agree with this.

**Comment by danimesq** [comment]
> A reputation system with invites, votes, and user optionally can pay a small verification fee to build a greater trust.

https://github.com/ZeroCoinOrganization/ZeroTrust

@imachug 
> First, we want to make a site for wallet so we need a site. I see there's https://github.com/ZeroCoinOrganization/Zerocoin-wallet, and it's empty. So I think I can put webpack there, as I'd want to use ES2017 features, like import of my local files and NPM packages.
> 
> I'd like to hear whether you agree with this.

I agree. As said, you can create the skeleton, then I create the design with VueJS.

**Comment by purplesyringa** [comment]
Okay, I'll start adding the skeleton then.

**Comment by d14na** [comment]
just setup a [Peepeth](https://peepeth.com/) account and I see they're using **ETH signatures** to batch txs (instead of having to write every update to the blockchain). here is a link to a Medium article explaining how it works https://medium.com/@abcoathup/evolution-of-decentralised-social-media-dfe567d23e54

My thoughts are that this would be a major improvement on the UX when interacting with a **blockchain-version** of a  system like ZeroMe or ZeroTalk. In the case of Peepeth, you only have to write to the blockchain once every 15 actions. How it all works under-the-hood is still a bit of a mystery to me, but I'll do some research soonish' and let you know my thoughts.

**Comment by danimesq** [comment]
@imachug
I don't think we need to base on something other than Bitcoin/Ripple for now, but what are your thoughts?

**Comment by purplesyringa** [comment]
We'll create our blockchain on JavaScript/Python mixture (in case we support BackgroundProcessing plugin).

We *can* use Bitcoin/WhateverCoin docs, or Etherium contacts as example, but we'll write the code ourselves, so we don't rely on other projects and we can license it.

**Comment by danimesq** [comment]
@imachug
Really it will need BackgroundProcessing, or the blockchain will be slow with the publication limit per seconds.
Yes, use Bitcoin/Ripple as inspiration for now, but Ethereum is more advanced, then let smart-contracts for when we rebrand it as Zerum.

**Comment by danimesq** [comment]
@imachug 
> Really it will need BackgroundProcessing, or the blockchain will be slow with the publication limit per seconds.

It is wrong. The 30 second publish limit is individual, not for all users, then it is good to prevent spam and will not make the network slow.

**Comment by danimesq** [comment]
@imachug
Thanks for the replies

**Comment by danimesq** [comment]
As said on a chat:
> Funding of open-Internet projects (ZeroNet, ShadowSocks, etc), being programmed in visual event sheets that even newbie users can audit and contribute, great TPS like EOS, having all current Bitcoin balances in a block (acting like a fork but not being one, making Bitcoin users to want to hold Zerocoin), anonymization and support to mining on browsers and support of smart contracts
